Secure Archiver implementation and tests
faberNovel/ADUtils pull request #27
Opened 2021-07-06 12:51 UTC by ThomasEsterlin

2021-07-06 15:01 UTC, laviallb requested changes

2021-07-06 15:01 UTC, laviallb commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private let installedKey: String
Je pense que cette partie doit etre extraite du secureArchiver car peut etre utiliser par d'autres objets

2021-07-06 15:01 UTC, laviallb commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private func getCryptoKey() -> SymmetricKey? {
Je pense que que tu peux stocker la valeur en RAM a l'init, et mettre un throw dans l'init, comme ca par la suite ca evite d'avoir des soucis de clé optionnelle, qui n'arrivent jamais de pas la conception du code

2021-07-06 15:01 UTC, laviallb commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private func randomString(length: Int) -> String {
Tu as pu regarder dans OWASP ce qu'ils disent pour la generation de random ?

2021-07-07 07:35 UTC, ThomasEsterlin commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private func getCryptoKey() -> SymmetricKey? {
Si on charge la clé à l'init, ça veut dire qu'elle peut potentiellement être supprimée sans que l'état de notre objet change. J'ai modifié le code pour throw une erreur au lieu de mettre des optionnels mais sans stocker cette valeur dans la RAM.

2021-07-07 07:36 UTC, ThomasEsterlin commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private let installedKey: String
Je n'ai pas compris cette partie

2021-07-07 07:37 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private let storageArchiver: StorageArchiver
en pratique le storage archiver ce sera très souvent userdefault, donc ce serait cool de fournir directement une conformance de UserDefault à StorageArchiver et de pouvoir ne pas le passer à l'init par défault.

2021-07-07 07:37 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private let storageArchiver: StorageArchiver
Et peut être pas besoin de la variable `defaults` du coup, tu pourrais utiliser le storageArchiver

2021-07-07 07:37 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private let keychainArchiver: KeychainArchiver
Pareil pour le keychain, ca vaudrait peut être le coup de fournir une implémentation par défault, hsitoire d'avoir le moins de setup à faire en pratique.

2021-07-07 07:37 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +        let isInstalled = defaults.bool(forKey: installedKey)
si l'app est pas installée, ca vaudrait le coup de clean le keychain, vu que les données sont persistées entre plusieurs lancements

2021-07-07 07:37 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +            if isInstalled {
pas besoin des deux ifs imbriqués, tu peux faire `if let storedPassphrase = keychainArchiver.get(forKey: passphraseKey), isInstalled {`

2021-07-07 07:37 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +import CryptoKit
on est obligé d'utiliser CryptoKit ? c'est ca qui force le iOS13+ right ?

2021-07-07 07:39 UTC, ThomasEsterlin commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private let storageArchiver: StorageArchiver
J'ai fait les des extensions dans mon projet de tests, Benjamin parlait de les mettre en snippets ou dans le readme

2021-07-07 07:40 UTC, ThomasEsterlin commented on Modules/ADUtils_security/SecureArchiver.swift
> +        let isInstalled = defaults.bool(forKey: installedKey)
Si elle est pas installée, on écrase la valeur de la passphrase, c'est comme un clean non ?

2021-07-07 07:42 UTC, ThomasEsterlin commented on Modules/ADUtils_security/SecureArchiver.swift
> +import CryptoKit
CryptoKit garantit une bonne sécurité, mais ça force iOS 13+ oui

2021-07-07 07:52 UTC, laviallb commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private let storageArchiver: StorageArchiver
1) On peut mettre l'extension sur UserDefaults qui implémente StorageArchiver dans ADUtils, comme il n'y a pas de dependance externe
2) Le defaults est actuellement utilisé pour verifier si on a deja lancer l'app depuis son installation, comme je dit [ici](https://github.com/faberNovel/ADUtils/pull/27#discussion_r664636480), je pense que cette logique peut etre sortie de cette classe

2021-07-07 07:53 UTC, laviallb commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private let keychainArchiver: KeychainArchiver
Le soucis c'est qu'en pratique on utilise KeychainAccess, qui est une librairie externe. Pour éviter de l'ajouter en dependance de ADUtils/Security je proposais de le mettre ou en snippet dans la lib de snippet, on dans le templater.

2021-07-07 07:55 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +        let isInstalled = defaults.bool(forKey: installedKey)
ah oui my bad, j'ai été perturbé par ton early return

2021-07-07 08:38 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private let keychainArchiver: KeychainArchiver
Mon point c'est justement que y'avais peut être pas besoin de KeychainAccess pour stocker juste une string dans le keychain et qu'on pourrait le faire à la mano pour cette classe.

2021-07-07 08:48 UTC, laviallb commented on Modules/ADUtils_security/SecureArchiver.swift
> +    private let keychainArchiver: KeychainArchiver
Ok je vois, c'est que KeychainAccess te permet quand meme de bien setup ton keychain, notamment si tu l'utilise dans des cas non triviaux, par exemple dans un app group

2021-07-09 13:02 UTC, laviallb commented
@felginep, tu en penses quoi de la PR dans cet état ? tu peux refaire une passe dessus ?

2021-07-09 13:21 UTC, felginep commented on ADUtilsTests/Security/PostInstallationKeychainCleanerTests.swift
> +                userDefaults.set(nil, forKey: "_PIKC_ALF")
indent bizarre

2021-07-09 13:21 UTC, felginep commented on ADUtilsTests/Security/PostInstallationKeychainCleanerTests.swift
> +                userDefaults.set(nil, forKey: "_PIKC_ALF")
+ ca sort d'où le naming `_PIKC_ALF`?

2021-07-09 13:21 UTC, felginep commented on ADUtilsTests/Security/PostInstallationKeychainCleanerTests.swift
> +                } catch {
y'a pas une méthode sur xctest qui fail si ca throw ? je crois même que tu as potentiellement même plus besoin du do {} catch {}, tu peux try directement dans le test

2021-07-09 13:21 UTC, felginep commented on ADUtilsTests/Security/SecureArchiverTests.swift
> +extension Car: Equatable {
besoin de cette conformance à la mano à equatable ?

2021-07-09 13:21 UTC, felginep commented on ADUtilsTests/Security/SecureArchiverTests.swift
> +                    if #available(iOS 13.0, *) {
peut être mettre le available sur la classe de test directement non ?

2021-07-09 13:21 UTC, felginep commented on ADUtilsTests/Security/SecureArchiverTests.swift
> +                        //Then
plusieurs `//Then` où il manque un espace

2021-07-09 13:21 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +    func get(forKey: String) -> String?
`getValue(forKey: String)` plutôt mb ? le get tout court je suis pas fan. Ou alors `value(forKey)` mais y'a peut être un risque de collistion avec `UserDefaults`

2021-07-09 13:21 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +    func get(forKey: String) -> String?
(pareil pour StorageArchiver)

2021-07-09 13:21 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +                storageArchiver: StorageArchiver,
on pourrait passer par défault `UserDefault.standard` ici

2021-07-09 13:21 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +                appKey: String) {
on a besoin du `appKey` ? on peut pas lui trouver une valeur par défault ?

2021-07-09 13:21 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +    public init(keychainArchiver: KeychainArchiver,
je continue à penser que ce serait cool d'avoir une valeur par défault du KeychainArchiver, histoire d'avoir 0 setup à faire dans le meilleur des cas

2021-07-09 13:22 UTC, felginep commented
J'ai refait une passe rapide. Y'a qq petits truc qu'on peut faire pour améliorer l'expérience d'intégration, mais sinon niveau logique LGTM

2021-07-09 13:30 UTC, laviallb commented on ADUtilsTests/Security/PostInstallationKeychainCleanerTests.swift
> +                userDefaults.set(nil, forKey: "_PIKC_ALF")
c'est arbitraire, j'ai mis les initiales, en fait j'etait un peu mitigé a mettre "isAlreadyLaunched" ou autre truc très explicite, parce que je me dit qu'en cas d'audit ca devient trivial de changer la valeur et/ou de comprendre ce à quoi il sert. Ca reste très léger mais mieux que rien.

2021-07-09 14:06 UTC, ThomasEsterlin commented on Modules/ADUtils_security/SecureArchiver.swift
> +                appKey: String) {
Le truc c'est que si tu passes pas d'appKey, je pense tu peux potentiellement écraser la clé d'une autre app si le dev utilise un mauvais KeychainArchiver (sans appGroup par exemple).

2021-07-09 18:18 UTC, felginep commented on Modules/ADUtils_security/SecureArchiver.swift
> +                appKey: String) {
ok pour l'appKey, mais du coup si tu utilises le bundle id de l'app tu t'en sors pas mal pour valeur par défault non?

2021-07-09 18:34 UTC, felginep commented on ADUtilsTests/Security/PostInstallationKeychainCleanerTests.swift
> +                try? postInstallationKeychainCleaner.checkInstallation()
tu perds l'intérêt d'utiliser un système d'erreur si tu met des `?`.
En fait c'est avec XCTets que tu peux throw directement. Si tu utilises Quick/Nimble comme ici il te faut wrap tout le test dans un expect
```
expect {
    ...
    try secureArchiver.set(myCar, forKey: "car")
    ...
}.toNot(throwError())
```

2021-07-16 08:07 UTC, felginep approved these changes

2021-07-28 07:16 UTC, laviallb approved these changes

2021-07-28 07:16 UTC, merged